// MorgenGrauen MUDlib
//
// materials.h -- material definitions
//
// This file is generated by /secure/materialdb.c
//
// DO NOT EDIT!
//
// $Id: materialdb.c 6930 2008-08-09 09:20:16Z Zesstra $

#ifndef __MATERIALS_H__
#define __MATERIALS_H__

// ****************************** Materialien ******************************

// Gruppe: Hoelzer
#define MAT_ASH_WOOD            "ash_wood"            // flexibel, magisch
#define MAT_BALSA               "balsa"               // weicher/leichter als Kork
#define MAT_BEECH               "beech"               // hart, roetlich
#define MAT_BIRCH               "birch"               // magisch, zaeh, suess
#define MAT_BRUYERE             "bruyere"             // sehr hart und zaeh, fuer Pfeifen
#define MAT_CEDAR               "cedar"               // magisch und weich
#define MAT_CORK                "cork"                // weich
#define MAT_EBONY               "ebony"               // schwarz
#define MAT_FIR                 "fir"                 // trocken (Douglasie)
#define MAT_IRON_WOOD           "iron_wood"           // extrem hart (tropisch)
#define MAT_LARIX               "larix"               // sehr harzig, biegsam
#define MAT_LIME                "lime"                // weich
#define MAT_MAHAGONI            "mahagoni"            // rot bis dunkelrot
#define MAT_MAPLE               "maple"               // Ahornholz
#define MAT_MISC_CONIFER_WOOD   "misc_conifer_wood"   // Nadelholz
#define MAT_MISC_DECIDUOUS_WOOD "misc_deciduous_wood" // Laubholz
#define MAT_MISC_TROPICAL_WOOD  "misc_tropical_wood"  // Tropenholz
#define MAT_MISC_WOOD           "misc_wood"           // Holz
#define MAT_NUTTREE             "nuttree"             // hell, polierfaehig
#define MAT_OAK                 "oak"                 // hart
#define MAT_PEAR_WOOD           "pear_wood"           // zaeh, trocken, magisch
#define MAT_PINE                "pine"                // harzig (Pinie, Kienspan)
#define MAT_POPLAR              "poplar"              // sehr weich, faserig
#define MAT_ROBINIA             "robinia"             // sehr hart
#define MAT_ROSEWOOD            "rosewood"            // schokoladenbraun
#define MAT_SANDAL              "sandal"              // gut riechend, kostbar, hart
#define MAT_SPRUCE              "spruce"              // trocken, bruechig
#define MAT_TEAK                "teak"                // Teakholz
#define MAT_WILLOW              "willow"              // weich und flexibel
#define MAT_WOODEN_PLANT        "wooden_plant"        // Pflanzen mit Holzanteil (Baeume, Gebuesche)
#define MAT_YEW                 "yew"                 // zaeh, biegsam

// Gruppe: Edelsteine
#define MAT_AMBER               "amber"               // Bernstein
#define MAT_AMETHYST            "amethyst"            // violett (Quarz)
#define MAT_AQUAMARINE          "aquamarine"          // blau
#define MAT_DIAMOND             "diamond"             // Diamant
#define MAT_EMERALD             "emerald"             // gruen
#define MAT_GARNET              "garnet"              // rot, Edelstein: Karfunkel
#define MAT_JADE                "jade"                // Jade
#define MAT_LAZURITE            "lazurite"            // tiefblau (ultramarin)
#define MAT_MISC_JEWEL          "misc_jewel"          // Edelstein
#define MAT_OCTARINE            "octarine"            // magischer Muell :)
#define MAT_OPAL                "opal"                // weiss, rot, blau, bunt
#define MAT_PEARL               "pearl"               // Perle
#define MAT_RUBY                "ruby"                // rot
#define MAT_SAPPHIRE            "sapphire"            // blau
#define MAT_TOPAZ               "topaz"               // gelb
#define MAT_TURQUOISE           "turquoise"           // Tuerkis

// Gruppe: Steine
#define MAT_SULFUR              "S"                   // gelb
#define MAT_AGATE               "agate"               // Farbspiel
#define MAT_ASBESTOS            "asbestos"            // grauweiss
#define MAT_ASPHALT             "asphalt"             // Asphalt
#define MAT_BARYT               "baryt"               // weiss, hohe Dichte
#define MAT_BASALT              "basalt"              // Basalt
#define MAT_CINNABAR            "cinnabar"            // bleigrau bis scharlachrot
#define MAT_CONCRETE            "concrete"            // Beton
#define MAT_CRYSTAL             "crystal"             // klar bis weiss
#define MAT_FLINT               "flint"               // Feuerstein
#define MAT_FLUORITE            "fluorite"            // oft fluoreszierend
#define MAT_GNEISS              "gneiss"              // Gneiss
#define MAT_GRANITE             "granite"             // Granit
#define MAT_GRAPHITE            "graphite"            // metallisch grau
#define MAT_LIMESTONE           "limestone"           // Kalkstein
#define MAT_MALACHITE           "malachite"           // Malachit
#define MAT_MARBLE              "marble"              // Marmor
#define MAT_MISC_MINERAL        "misc_mineral"        // allg. Mineralien
#define MAT_MISC_STONE          "misc_stone"          // allg. Gestein
#define MAT_MOONSTONE           "moonstone"           // gelb, blaeulich, fahl
#define MAT_OBSIDIAN            "obsidian"            // schwarz
#define MAT_OLIVIN              "olivin"              // gruen bis braun
#define MAT_ONYX                "onyx"                // Unterart Achat, schwarz
#define MAT_ORTHOKLAS           "orthoklas"           // weiss bis grau, gruenlich
#define MAT_QUARTZ              "quartz"              // klar bis grau, auch gelb
#define MAT_SLATE               "slate"               // Schiefer
#define MAT_TOOTH               "tooth"               // Zahn

// Gruppe: anziehende Materialien
#define MAT_COBALT              "Co"                  // hartes, sproedes Legierungmet.
#define MAT_IRON                "Fe"                  // weich
#define MAT_HOWALGO             "howalgo"             // Zwergenwaffenstahl
#define MAT_MISC_MAGNETIC       "misc_magnetic"       // magnetisches Material
#define MAT_STEEL               "steel"               // hart, flexibel

// Gruppe: Metalle
#define MAT_SILVER              "Ag"                  // weiss
#define MAT_ALUMINIUM           "Al"                  // weich behandelt hart
#define MAT_GOLD                "Au"                  // weiss bis gelb/rot
#define MAT_COPPER              "Cu"                  // weich, rot
#define MAT_MERCURY             "Hg"                  // Quecksilber
#define MAT_IRIDIUM             "Ir"                  // schwer, giftig
#define MAT_MAGNESIUM           "Mg"                  // brennbar
#define MAT_SODIUM              "Na"                  // Wasser-Vorsicht
#define MAT_NEUTRONIUM          "Neutr"               // ultraschwer, unzerstoerbar
#define MAT_OSMIUM              "Os"                  // schwerstes Metall
#define MAT_LEAD                "Pb"                  // Blei
#define MAT_PLATINUM            "Pt"                  // grauweiss
#define MAT_TIN                 "Sn"                  // sehr weich, weiss
#define MAT_TITANIUM            "Ti"                  // aeusserst hart
#define MAT_TUNGSTEN            "W"                   // sehr hart, hitzebestaendig
#define MAT_ADAMANT             "adamant"             // hartes Elfenmetall
#define MAT_ANTIMON             "antimon"             // weich, sproede, silberweiss
#define MAT_ARSENIC             "arsenic"             // giftiges Halbmetall
#define MAT_BRASS               "brass"               // bis 80% Kupfer, Rest Zink
#define MAT_BRONCE              "bronce"              // Kupferlegierung (mit Zinn)
#define MAT_CHROMIUM            "chromium"            // silberweiss, weich, zaeh
#define MAT_ELEKTRON            "elektron"            // bis 75% Gold, Rest Silber
#define MAT_JOFIUM              "jofium"              // Jofium
#define MAT_MISC_METAL          "misc_metal"          // allg. Metall
#define MAT_MITHRIL             "mithril"             // Zwergenruestungsmetall
#define MAT_NICKEL              "nickel"              // zaeh, fest, silberweiss
#define MAT_THALLIUM            "thallium"            // giftig, schwer, weich
#define MAT_ZINC                "zinc"                // weich, bestaendig

// Gruppe: Drogen und Heiltraenke
#define MAT_ASPIRIN             "aspirin"             // Aspirin
#define MAT_CANNABIS            "cannabis"            // auch THC
#define MAT_COCAINE             "cocaine"             // Kokain
#define MAT_MISC_DRUG           "misc_drug"           // allg. Drogen
#define MAT_MORPHIUM            "morphium"            // Morphium
#define MAT_OPIUM               "opium"               // Opium
#define MAT_PENICILLIN          "penicillin"          // Penicillin
#define MAT_WECKAMIN            "weckamine"           // Aufputschmittel

// Gruppe: pflanzliche Materialien
#define MAT_MISC_HERBAL         "misc_herbal"         // allg. Kraeuter
#define MAT_MISC_PLANT          "misc_plant"          // allg. planzliches Material ohne Holzanteil
#define MAT_STRAW               "straw"               // Stroh

// Gruppe: biegsame Materialien
#define MAT_CHIFFON             "chiffon"             // Chiffon
#define MAT_CLOTH               "cloth"               // Stoff
#define MAT_COTTON              "cotton"              // Baumwolle
#define MAT_FEATHER             "feather"             // Federn
#define MAT_FELT                "felt"                // Filz
#define MAT_HAIR                "hair"                // Haare
#define MAT_LACE                "lace"                // Spitze
#define MAT_LATEX               "latex"               // Gummi
#define MAT_LEATHER             "leather"             // Leder
#define MAT_LINEN               "linen"               // Leinen
#define MAT_MISC_FLEXIBLE       "misc_flexible"       // biegsames Material
#define MAT_PAPER               "paper"               // Papier
#define MAT_PAPYRUS             "papyrus"             // Papyrus
#define MAT_PATENT_LEATHER      "patent_leather"      // Kunstleder
#define MAT_PELT                "pelt"                // Fell
#define MAT_PERGAMENT           "pergament"           // Pergament
#define MAT_SATIN               "satin"               // Satin
#define MAT_SILK                "silk"                // Seide
#define MAT_SKIN                "skin"                // Haut
#define MAT_VELVET              "velvet"              // Samt
#define MAT_WOOL                "wool"                // Wolle

// Gruppe: biologische Materialien
#define MAT_BLOOD               "blood"               // Blut
#define MAT_BONE                "bone"                // Knochen
#define MAT_CARTON              "carton"              // Pappe
#define MAT_CHITIN              "chitin"              // Chitin
#define MAT_FAT                 "fat"                 // Fett
#define MAT_FLESH               "flesh"               // Fleisch
#define MAT_FUNGUS              "fungus"              // Pilz
#define MAT_GHOST               "ghost"               // Geist
#define MAT_HORN                "horn"                // Horn
#define MAT_IVORY               "ivory"               // Elfenbein
#define MAT_MISC_DEAD           "misc_dead"           // allg. totes Material
#define MAT_MISC_LIVING         "misc_living"         // allg. lebendes Material
#define MAT_PEARLMOTHER         "pearlmother"         // Perlmutt
#define MAT_TALLOW              "tallow"              // Talg

// Gruppe: Saeuren
#define MAT_MISC_ACID           "misc_acid"           // Saeure

// Gruppe: Laugen
#define MAT_MISC_BASE           "misc_base"           // Lauge

// Gruppe: Gifte
#define MAT_PHOSPHORUS          "P"                   // Phosphor
#define MAT_PLUTONIUM           "Pu"                  // Plutonium
#define MAT_CHLOR               "chlor"               // Chlorgas
#define MAT_MISC_POISON         "misc_poison"         // giftiges Material

// Gruppe: Sprengstoffe
#define MAT_GUNPOWDER           "gunpowder"           // Schwarzpulver
#define MAT_LAUGHING_GAS        "laughing_gas"        // Lachgas
#define MAT_METHANE             "methane"             // Methan
#define MAT_MISC_EXPLOSIVE      "misc_explosive"      // allg. Sprengstoffe
#define MAT_NITROGLYCERINE      "nitroglycerine"      // Nitroglycerin
#define MAT_DETONATING_GAS      "oxyhydrogen"         // Knallgas
#define MAT_TNT                 "tnt"                 // TNT

// Gruppe: entflammbare Materialien
#define MAT_CARBON              "C"                   // Kohlenstoff
#define MAT_ALCOHOL             "alcohol"             // Alkohol
#define MAT_OIL                 "oil"                 // Oel

// Gruppe: (altertuemliche) Elemente
#define MAT_AIR                 "air"                 // Luft
#define MAT_EARTH               "earth"               // Erde
#define MAT_FIRE                "fire"                // Feuer
#define MAT_WATER               "water"               // Wasser

// Gruppe: geladene Materialien
#define MAT_LIGHTNING           "lightning"           // Blitz

// Gruppe: Magisches
#define MAT_MISC_MAGIC          "misc_magic"          // allg. magisches Material, das sich nicht naeher bestimmen laesst (wie Oktarin, Birnbaumholz)

// Gruppe: heilige Materialien
#define MAT_MISC_HOLY           "misc_holy"           // heiliges Material

// Gruppe: daemonische Materialien
#define MAT_MISC_UNHOLY         "misc_unholy"         // unheiliges Material

// Gruppe: unsichtbare Materialien
#define MAT_HELIUM              "He"                  // Helium
#define MAT_MISC_GAS            "misc_gas"            // allg. Gas
#define MAT_MISC_INVIS          "misc_invis"          // allg. unsichtbares Material

// Gruppe: feste Materialien
#define MAT_CERAMIC             "ceramic"             // Keramik
#define MAT_CHALK               "chalk"               // Kreide
#define MAT_CLAY                "clay"                // Ton
#define MAT_DUST                "dust"                // Staub
#define MAT_GLASS               "glass"               // Glas
#define MAT_ICE                 "ice"                 // Eis
#define MAT_MISC_FOOD           "misc_food"           // Essen
#define MAT_MISC_SOLID          "misc_solid"          // allg. Feststoffe
#define MAT_SALT                "natriumchloride"     // Kochsalz
#define MAT_PLASTIC             "plastic"             // Kunststoff
#define MAT_SALPETER            "salpeter"            // Salpeter
#define MAT_SAND                "sand"                // Sand
#define MAT_SHIT                "shit"                // Scheisse
#define MAT_SOAP                "soap"                // Seife
#define MAT_TAR                 "tar"                 // Teer
#define MAT_WAX                 "wax"                 // Wachs

// Gruppe: Fluessigkeiten
#define MAT_INK                 "ink"                 // Tinte
#define MAT_MILK                "milk"                // Milch
#define MAT_MISC_FLUID          "misc_fluid"          // allg. Fluessigkeit
#define MAT_PARFUM              "parfum"              // Parfuem
#define MAT_SLIME               "slime"               // Schleim

// Gruppe: Gase
// sonstige Materialien:
#define MAT_MISC                "misc"                // allg. Material (default)
#define MAT_SHADOW              "shadow"              // Schatten

// **************************** Materialgruppen ****************************

#ifndef _IS_MATERIALDB_
#define MATGROUP_ACIDIC            "mg_acidic"         // Saeuren
#define MATGROUP_BASIC             "mg_basic"          // Laugen
#define MATGROUP_BIO               "mg_bio"            // biologische Materialien
#define MATGROUP_CLOTH             "mg_cloth"          // Stoffe
#define MATGROUP_CONIFER_WOOD      "mg_conifer_wood"   // Nadelhoelzer
#define MATGROUP_DEAD              "mg_dead"           // Ueberreste von Lebewesen
#define MATGROUP_DECIDUOUS_WOOD    "mg_deciduous_wood" // Laubhoelzer
#define MATGROUP_DRUG              "mg_drug"           // Drogen und Heiltraenke
#define MATGROUP_EATABLE           "mg_eatable"        // Essbares
#define MATGROUP_ELECTRICAL        "mg_electrical"     // geladene Materialien
#define MATGROUP_ELEMENTAL         "mg_elemental"      // (altertuemliche) Elemente
#define MATGROUP_EXPLOSIVE         "mg_explosive"      // Sprengstoffe
#define MATGROUP_FLEXIBLE          "mg_flexible"       // biegsame Materialien
#define MATGROUP_FLUID             "mg_fluid"          // Fluessigkeiten
#define MATGROUP_GAS               "mg_gas"            // Gase
#define MATGROUP_HERBAL            "mg_herbal"         // pflanzliche Materialien
#define MATGROUP_HOLY              "mg_holy"           // heilige Materialien
#define MATGROUP_INFLAMMABLE       "mg_inflammable"    // entflammbare Materialien
#define MATGROUP_INVIS             "mg_invis"          // unsichtbare Materialien
#define MATGROUP_JEWEL             "mg_jewel"          // Edelsteine
#define MATGROUP_LIVING            "mg_living"         // Lebewesen
#define MATGROUP_MAGIC             "mg_magic"          // Magisches
#define MATGROUP_MAGNETIC          "mg_magnetic"       // anziehende Materialien
#define MATGROUP_METAL             "mg_metal"          // Metalle
#define MATGROUP_MINERAL           "mg_mineral"        // Mineralien
#define MATGROUP_MISC              "mg_misc"           // verschiedene Materialien, die nicht naeher zugeordnet sind (als fest, fluessig, gasfoermig)
#define MATGROUP_PAPER             "mg_paper"          // Papieraehliches
#define MATGROUP_POISONOUS         "mg_poisonous"      // Gifte
#define MATGROUP_PRECIOUS_METAL    "mg_precious_metal" // Edelmetalle
#define MATGROUP_RADIOACTIVE       "mg_radioactive"    // Unbeschreibliches
#define MATGROUP_SOLID             "mg_solid"          // feste Materialien
#define MATGROUP_STONE             "mg_stone"          // Steine
#define MATGROUP_TROPICAL_WOOD     "mg_tropical_wood"  // Tropenhoelzer
#define MATGROUP_UNHOLY            "mg_unholy"         // daemonische Materialien
#define MATGROUP_WOOD              "mg_wood"           // Hoelzer


#endif // _IS_MATERIALDB_
#endif // __THING_MATERIAL_H__
